### ISSUE TITLE
BUG: Stackable Discs duplicating from jukebox

### ISSUE THREAD

**Issue by TravelTimN** [JEFF-Media-GbR/StackResize#3]
plugin-version: **1.5.4**
config-version: **202306270727**
regex: **^MUSIC_DISC_.*$: 64**

Minecraft: **1.20.1 Java SMP with Bedrock** (*Geyser + Floodgate*)

Bug Replication:
- Hold 2 or more of the same disc in inventory/hand.
- Place 1 of the discs into a jukebox to play music.
- Take the disc out, and now you've got a duplicated disc.

The more you duplicate, the faster it duplicates the overall quantity.
You can go from 2 of the same disc, to a full stack, in only playing the disc 6 times in the jukebox.

Pattern seems to be:
2 discs [d] > 3d > 5d > 9d > 17d > 33d > 65d > etc.
+1 > +2 > +4 > +8 > +16 > +32 > etc.

Holding only 1 of a disc has the appearance of duplicating when taking out the disc, but no actual duplication occurs.

`config.yml`
> no changes from original source

--- 

`max-stack-sizes.yml`
```yml
static:
  BRUSH: 64
  DIRT: 64
  EGG: 64
  ENCHANTED_BOOK: 64
  ENDER_PEARL: 64
  FLINT_AND_STEEL: 64
  LINGERING_POTION: 64
  POTION: 64
  SADDLE: 64
  SHEARS: 64
  SNOWBALL: 64
  SPLASH_POTION: 64
  TOTEM_OF_UNDYING: 1

regex:
  ^.*_BANNER_PATTERN: 64 # ALL banners
  ^.*_?BED: 64 # ALL beds
  ^.*_?BOAT: 64 # ALL boats
  ^.*_BOTTLE: 64 # ALL bottles, including honey, water, experience
  ^.*_?BUCKET$: 64 # All buckets
  ^.*_CHESTPLATE$: 1 # All chestplates
  ^.*_HORSE_ARMOR: 64 # ALL horse armors
  ^.*_ON_A_STICK$: 64 # ALL items on a stick
  ^.*_?MINECART$: 64 # All minecarts
  ^MUSIC_DISC_.*$: 64 # All music discs
  ^.*_?RAFT: 64 # ALL rafts
  ^.*_SIGN: 64 # ALL signs, including hanging
  ^.*_SOUP: 64 # ALL soups
  ^.*_STEW: 64 # ALL stews
  ^.*_WOOL$: 64 # All colored wool
```
